name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Obtener SHA corto
        id: vars
        run: echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      -
        name: Usar la variable de entorno
          run: |
            echo "La variable COMMIT_ID ahora vale: $COMMIT_ID"
            # También puedes usarla mediante el contexto de env
            echo "Desde el contexto: ${{ env.COMMIT_ID }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: stivenparada/python-app:${{ env.COMMIT_ID }}